version: 2
sources:
  - name: staging
    database: dataengineerproject-448203
    schema: chicago_traffic_crashes


    tables:
      - name: vehicle_data
      - name: crash_data
      - name: person_data
      